"""Shared exclusion logic for all coding-standards hooks.

A file is excluded from coding-standards enforcement if ANY of:

1. Its path matches a built-in default pattern (shadcn/ui, generated code,
   migrations, vendored deps, build outputs, lock files).
2. Its content has a generation marker in the first 10 lines (`@generated`,
   `DO NOT EDIT`, `Code generated by`, etc.).
3. Its path matches a pattern in the project's `.coding-standards-ignore`
   (gitignore-style, located at the project root).

Stdlib only. Used by every block-*.py hook and (via the SKILL.md directive)
by the orchestrator and workers.
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Iterable

# ─────────────────────────────────────────────────────────────────────────────
# Built-in default exclusions.
# Patterns are gitignore-style:
#   `*` matches any single path segment (no `/`)
#   `**` matches zero or more path segments
#   patterns without `/` match by filename anywhere
# ─────────────────────────────────────────────────────────────────────────────

DEFAULT_EXCLUSIONS: tuple[str, ...] = (
    # Vendored / installed deps
    "**/node_modules/**",
    "**/vendor/**",
    "**/bower_components/**",

    # shadcn/ui — generated components, owned by shadcn CLI, NOT user code.
    # Modifying these breaks the upgrade path (re-running shadcn add wipes them).
    "**/components/ui/**",
    "**/src/components/ui/**",
    "**/app/components/ui/**",
    # Some projects put them at the registry path
    "**/registry/ui/**",

    # ORM / migration tooling — output is owned by the tool, not the human.
    "**/prisma/migrations/**",
    "**/drizzle/migrations/**",
    "**/drizzle/meta/**",
    "**/.prisma/**",
    "**/alembic/versions/**",      # Python — Alembic
    "**/migrations/[0-9][0-9][0-9][0-9]_*.py",  # Django (e.g. 0001_initial.py)
    "**/db/migrate/**",            # Rails
    "**/*.designer.cs",            # .NET designer files
    "**/Migrations/**",            # EF Core
    "**/internal/sqlc/**",         # Go - sqlc generated

    # Codegen output — GraphQL, OpenAPI, protobuf, etc.
    "**/generated/**",
    "**/__generated__/**",
    "**/_generated/**",
    "**/.generated/**",
    "**/*.gen.ts",
    "**/*.gen.tsx",
    "**/*.gen.js",
    "**/*.gen.jsx",
    "**/*.generated.ts",
    "**/*.generated.tsx",
    "**/*.generated.js",
    "**/*.generated.jsx",
    "**/*_pb.go",                  # protobuf
    "**/*.pb.go",                  # protobuf
    "**/*_grpc.pb.go",             # gRPC
    "**/*.pb.cc",
    "**/*.pb.h",
    "**/zz_generated.*",           # Go conventional generated prefix
    "**/*_generated.go",

    # Framework build / output dirs
    "**/dist/**",
    "**/build/**",
    "**/.next/**",
    "**/.nuxt/**",
    "**/.svelte-kit/**",
    "**/.angular/**",
    "**/.cache/**",
    "**/target/**",                # Java / Rust
    "**/bin/**",                   # .NET
    "**/obj/**",                   # .NET
    "**/out/**",
    "**/public/build/**",
    "**/storage/framework/**",     # Laravel

    # Lock files — modified by package managers, not by humans
    "**/package-lock.json",
    "**/yarn.lock",
    "**/pnpm-lock.yaml",
    "**/composer.lock",
    "**/Cargo.lock",
    "**/go.sum",
    "**/poetry.lock",
    "**/Pipfile.lock",
    "**/uv.lock",

    # Auto-generated config / typing
    "**/next-env.d.ts",            # Next.js
    "**/env.d.ts",                 # Vite/Nuxt
    "**/.eslintcache",
    "**/tsconfig.tsbuildinfo",

    # IDE / editor metadata
    "**/.idea/**",
    "**/.vscode/extensions.json",
    "**/.DS_Store",

    # Test snapshots — owned by test framework
    "**/__snapshots__/**",
    "**/*.snap",

    # Cocos Creator engine-managed dirs
    "**/library/**",
    "**/temp/**",
    "**/settings/**",

    # Spring Boot Gradle/Maven build state
    "**/.gradle/**",
    "**/HELP.md",

    # Compiled Python
    "**/__pycache__/**",
    "**/*.pyc",
    "**/*.pyo",
)

# Markers that indicate the file is generated. Checked against the first
# 10 lines of file content (case-insensitive substring match).
GENERATION_MARKERS: tuple[str, ...] = (
    "@generated",
    "do not edit",
    "automatically generated",
    "auto-generated",
    "auto generated",
    "code generated by",
    "this file is generated",
    "this file was generated",
    "@autogenerated",
    "@codegen",
    "@nocheck",  # Common in generated TS files
)


def _segment_to_regex(segment: str) -> str:
    """Convert a single path segment (no `/`) glob to a regex body.

    Within a segment, `*` matches any chars except `/`, `?` matches one char
    except `/`, `[..]` is a character class.
    """
    out: list[str] = []
    i = 0
    while i < len(segment):
        ch = segment[i]
        if ch == "*":
            out.append(r"[^/]*")
            i += 1
        elif ch == "?":
            out.append(r"[^/]")
            i += 1
        elif ch == "[":
            end = segment.find("]", i + 1)
            if end == -1:
                out.append(re.escape(ch))
                i += 1
            else:
                out.append(segment[i : end + 1])
                i = end + 1
        else:
            out.append(re.escape(ch))
            i += 1
    return "".join(out)


def _pattern_to_regex(pattern: str) -> re.Pattern[str]:
    """Convert a gitignore-style glob pattern to a compiled regex.

    Semantics:
      `*`     within a segment, matches any chars except `/`
      `**/`   at start: matches zero or more leading directory segments (incl. trailing `/`)
      `/**`   at end: matches `/anything` or nothing (the directory's contents)
      `/**/`  in middle: matches `/anything/` between two literal segments
      `?`     matches one char except `/`
      `[..]`  character class

    Pattern without `/` matches by filename anywhere in the path.
    Pattern starting with `/` is anchored at path start.
    Pattern with `/` (but not leading) matches at any path depth.
    """
    if "/" not in pattern:
        body = _segment_to_regex(pattern)
        return re.compile(rf"(?:^|.*/)({body})$")

    out: list[str] = []
    i = 0
    n = len(pattern)
    while i < n:
        # Order matters — match multi-char sequences first.
        if pattern.startswith("**/", i):
            # `**/` — zero or more leading segments (or empty).
            # `.+/` matches at least one char + trailing `/`. `?` makes the
            # whole group optional, so `**/foo` matches `foo` at depth 0 too.
            out.append(r"(?:.+/)?")
            i += 3
            continue
        if pattern.startswith("/**", i):
            if i + 3 == n:
                # Trailing `/**` — match `/anything` or nothing.
                out.append(r"(?:/.*)?")
                i += 3
                continue
            if i + 3 < n and pattern[i + 3] == "/":
                # `/**/` — match `/` + zero or more segments + `/`.
                out.append(r"/(?:[^/]+/)*")
                i += 4
                continue
            # `/**foo` (uncommon) — fall through to single `/`
        if pattern[i] == "*":
            if i + 1 < n and pattern[i + 1] == "*":
                # Bare `**` not at a recognized boundary — treat as `.*`.
                out.append(r".*")
                i += 2
                continue
            out.append(r"[^/]*")
            i += 1
            continue
        if pattern[i] == "?":
            out.append(r"[^/]")
            i += 1
            continue
        if pattern[i] == "[":
            end = pattern.find("]", i + 1)
            if end == -1:
                out.append(re.escape(pattern[i]))
                i += 1
            else:
                out.append(pattern[i : end + 1])
                i = end + 1
            continue
        # Literal character (including `/`).
        out.append(re.escape(pattern[i]))
        i += 1

    body = "".join(out)
    if pattern.startswith("/"):
        return re.compile(rf"^{body}$")
    # Non-leading-slash patterns that contain a `/` match at ANY path depth
    # (per this function's docstring). The hook receives an ABSOLUTE file_path,
    # so anchor the body at a directory boundary with `(?:^|.*/)` — mirroring
    # the bare-filename branch above. `(?:^|/)` alone is unreachable under
    # re.Pattern.match() (it can only take the `^` branch at offset 0), which
    # made patterns like `src/third-party/**` silently fail on absolute paths.
    return re.compile(rf"(?:^|.*/){body}$")


# Cache compiled regex per pattern.
_REGEX_CACHE: dict[str, re.Pattern[str]] = {}


def _compile_cached(pattern: str) -> re.Pattern[str]:
    if pattern not in _REGEX_CACHE:
        _REGEX_CACHE[pattern] = _pattern_to_regex(pattern)
    return _REGEX_CACHE[pattern]


def matches_any_pattern(path_str: str, patterns: Iterable[str]) -> str | None:
    """Return the first pattern that matches `path_str`, or None.

    `path_str` is normalized to forward slashes regardless of platform so the
    same patterns work on Windows and Unix.
    """
    normalized = path_str.replace("\\", "/")
    for pattern in patterns:
        if _compile_cached(pattern).match(normalized):
            return pattern
    return None


def find_project_root(start: Path) -> Path | None:
    """Walk up from `start` to find a project root marker.

    A project root is the first ancestor directory containing any of:
    `.coding-standards-ignore`, `.git`, `package.json`, `pyproject.toml`,
    `Cargo.toml`, `go.mod`, `composer.json`, `pom.xml`, `build.gradle`,
    `requirements.txt`/`setup.py`/`setup.cfg` (plain Python), or a `*.csproj` /
    `*.sln` / `*.fsproj` file (.NET — matched by glob, not exact name).
    Returns None if no marker is found within 20 levels.
    """
    markers = {
        ".coding-standards-ignore", ".git", "package.json", "pyproject.toml",
        "Cargo.toml", "go.mod", "composer.json", "pom.xml", "build.gradle",
        "build.gradle.kts", "requirements.txt", "setup.py", "setup.cfg",
    }
    glob_markers = ("*.csproj", "*.sln", "*.fsproj")
    current = start if start.is_dir() else start.parent
    for _ in range(20):
        if any((current / m).exists() for m in markers):
            return current
        if any(next(current.glob(g), None) is not None for g in glob_markers):
            return current
        if current.parent == current:
            return None
        current = current.parent
    return None


def load_user_ignore_patterns(project_root: Path | None) -> tuple[str, ...]:
    """Load patterns from `.coding-standards-ignore` at the project root.

    Returns empty tuple if no such file exists or project_root is None.
    Lines starting with `#` and blank lines are ignored.
    """
    if project_root is None:
        return ()
    ignore_file = project_root / ".coding-standards-ignore"
    if not ignore_file.exists():
        return ()
    try:
        lines = ignore_file.read_text(encoding="utf-8").splitlines()
    except (OSError, UnicodeDecodeError):
        return ()
    patterns = []
    for line in lines:
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        patterns.append(line)
    return tuple(patterns)


def is_excluded_path(file_path: str) -> tuple[bool, str | None]:
    """Check if a file path is excluded by any default or user pattern.

    Returns (excluded, matched_pattern_or_None).
    """
    # Defaults
    match = matches_any_pattern(file_path, DEFAULT_EXCLUSIONS)
    if match:
        return True, f"default:{match}"

    # User-defined
    project_root = find_project_root(Path(file_path))
    user_patterns = load_user_ignore_patterns(project_root)
    if user_patterns:
        match = matches_any_pattern(file_path, user_patterns)
        if match:
            return True, f"user:{match}"

    return False, None


def has_generation_marker(content: str, max_lines: int = 10) -> str | None:
    """Return the first generation marker found in the first `max_lines`
    lines of `content`, or None.
    """
    if not content:
        return None
    head = content.splitlines()[:max_lines]
    head_text = "\n".join(head).lower()
    for marker in GENERATION_MARKERS:
        if marker in head_text:
            return marker
    return None
